services:
  judge0:
    image: judge0/judge0:latest-dev
    build:
      context: .
      target: development
    volumes:
      - .:/api
    ports:
      - "2358:2358"
      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true

  db:
    image: postgres:14.3
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:6.2.7
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data:
